### ISSUE TITLE
Update Artwork to Make Game More Playable

### ISSUE THREAD

**Issue by bronhuston** [UCSB-CS56-Projects/cs56-games-snake#13]
Depends on #16 
Currently, the "apple" the snake is trying to eat is smaller than the size of the snake, and is placed such that when the snake eats it, the apple is offset from the center of the snake. This makes it difficult to judge the exact location of the apple in relation to the snake. 

To improve the playability of the game the size or location of the apple could be altered.

~estimated 120

**Comment by zhanchengqian** [comment]
F16 OK
