### ISSUE TITLE
Refactor SnakeFrame into multiple objects/files

### ISSUE THREAD

**Issue by bronhuston** [UCSB-CS56-Projects/cs56-games-snake#16]
Currently, almost the entirety of the Snake game is made and controlled in the SnakeFrame.java file. The Gui, game controls, graphics, game logic and more are all in the same file. 

The game should be refactored into multiple files for the different objects required for the game. There should be separate files to handle the JFrame/GUI, snake object, level generation, graphics, etc. 

The code should be refactored and cleaned up before any additional functionality is added to the game.

~estimated 400

**Comment by zhanchengqian** [comment]
F16 OK
