### ISSUE TITLE
Ingame Bar

### ISSUE THREAD

**Issue by eshong** [UCSB-CS56-Projects/cs56-games-snake#25]
Sometimes the fruit will appear under the text of one of the above things, making it difficult to see. 
Add a bar for Score, High Score, Time, and Pause options + mouse interaction so that they 
do not have to overlap with snake and fruits.

**Comment by alecharrell** [comment]
Approved ~200 pts A.H.

**Comment by robingorge** [comment]
now fruits will not appear under the time. Also we have a game bar in game, it's more obvious for users to see the score and the time. And the mouse interaction about pause menu is in #24
