### ISSUE TITLE
2-player-mode problem

### ISSUE THREAD

**Issue by robingorge** [UCSB-CS56-Projects/cs56-games-snake#29]
2-player-mode has some problem to fix:the yellow snake always wins in the game.When it hits the blue snake the game will not end.

estimated point: 200 points

**Comment by omeedrabani** [comment]
Approved: 200 pts

**Comment by dlynch305** [comment]
Implemented M16

**Comment by zhanchengqian** [comment]
F16 OK (100 pts)
