### ISSUE TITLE
Create the rank of the scores in the menu

### ISSUE THREAD

**Issue by robingorge** [UCSB-CS56-Projects/cs56-games-snake#40]
For now it can only save the highest score. Make a new menu that could show the rank of the highest scores.

estimate: 200

**Comment by omeedrabani** [comment]
W16 OK

**Comment by dlynch305** [comment]
Partially completed M16. Third high score index not being used.

100 pts to bugfix

**Comment by Rmjiang7** [comment]
Buggy, delegated to new issue.
