### ISSUE TITLE
Adding special food

### ISSUE THREAD

**Issue by markwu35** [UCSB-CS56-Projects/cs56-games-snake#44]
Special food gives snake special abilities or effect, for example gaining more length, being able to eat player2's tail, slowing down snake speed.

**Comment by marcellisb** [comment]
Recommended Estimate: 300

**Comment by dlynch305** [comment]
M16

**Comment by zhanchengqian** [comment]
F16 OK

**Comment by zhanchengqian** [comment]
250 pts
