### ISSUE TITLE
Restructure the SnakeFrame class

### ISSUE THREAD

**Issue by marcellisb** [UCSB-CS56-Projects/cs56-games-snake#51]
Instead of painting the gui and using only a single mouseListener and KeyListener on SnakeFrame, separate components should be added to the frame so that each can have its own listeners and be clickable. GUI would be more intuitive.

Recommended estimate: 300 (if SnakeFrame refactoring still needs to be done, it's a mess at this point).

**Comment by dlynch305** [comment]
M16 OK

**Comment by zhanchengqian** [comment]
F16 OK
